# site
title: povis
baseurl: ""
url: http://povis.me

# posts
date_format: "%Y"
post_title: Story
post_date: Year
post_cat: Genre

# tooltips and short descriptions
hedera_eye_descr: music project
papers_descr: my white papers about software engineering

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  hedera-eye:
    output: true
    permalink: /:collection/:title
  papers:
    output: true

plugins:
  - jekyll-font-awesome-sass

font-awesome:
  assets: true