# site
title: Sergey Povisenko
baseurl: ""
url: ""
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1

# posts
date_format: "%Y"
post_title: Story
post_date: Year
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock


collections:
  hedera-eye:
    output: true
    permalink: /:collection/:title
  papers:
    output: true

plugins:
  - jekyll-font-awesome-sass

font-awesome:
  assets: true