# site
title: Sergey Povisenko
baseurl: ""
url: ""
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1

# bio
header: Sergey Povisenko
desc: >
  developing

# posts
date_format: "%Y"
post_title: Story
post_date: Year
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  recordings:
    output: true
  articles:
    output: true